lib/fileutils.rb
test/fileutils/test_fileutils.rb

`FileUtis.cp_r` with `remove_destination` cannot overwrite a symlink.  Though comment of `cp_r` doesn't provide a detail of this flag, it is good to remove destination symlink file to follow its name.
This problem is same as [Bug #13914](https://bugs.ruby-lang.org/issues/13914).
```ruby
require 'fileutils'
#
#
FileUtils.rm_rf 'tmp'
%w(tmp/src tmp/dest tmp/src/dir).each do|path|
FileUtils.mkdir_p path
end
File.symlink 'dir', 'tmp/src/a'
FileUtils.cp_r 'tmp/src', 'tmp/dest/', remove_destination: true
FileUtils.cp_r 'tmp/src', 'tmp/dest/', remove_destination: true # <- Errno::EEXIST exception is raised
```
```ruby
$ ruby bug.rb
Traceback (most recent call last):
13: from bug.rb:18:in `<main>'
12: from /usr/local/lib/ruby/2.5.0/fileutils.rb:390:in `cp_r'
11: from …
```

FileUtis.cp_r cannot overwrite a symlink of directory

---

lib/fileutils.rb

There's two changes here, one to use rbconfig instead of RUBY_PLATFORM to detect host operating system, and the remove_entry_secure changes relating to opening a dir as a file (mentioned in #17).
These are the only diffs that JRuby has from MRI's stdlib fileutils.rb. If these are incorporated into the fileutils gem, we can eliminate our copy.

JRuby tweaks

---

lib/fileutils.rb
test/fileutils/test_fileutils.rb

Contrary to `Dir.chdir`, `FileUtils.chdir` ignores the result of the block.
This fixes it.
Should this be committed to MRI's trunk, or here?

FileUtils.cd now returns result of block, if given

---

test/fileutils/test_fileutils.rb

Maybe fixes https://travis-ci.org/ruby/fileutils/jobs/378545293

Extend timeout second for test_assert_output_lines with JRuby

---

lib/fileutils.rb

Also, fixed the argument name to be the same as the actual argument name.
Ref: https://github.com/ruby/fileutils/blob/64e2750f095524f89df16c8ac5981207f9a4d9f2/lib/fileutils.rb#L474

Add missing `remove_destination` option to a doc [ci skip]

---

fileutils.gemspec
lib/fileutils.rb
lib/fileutils/version.rb

_Replaces #15._
Use already defined constant FileUtils::VERSION instead of duplicating
the information. Also move FileUtils::VERSION into its own file.
I moved FileUtils::VERSION into its own file to reduce warnings about already defined constants that happened with `gem build`.
In the gemspec, the require statement for the ruby core repository assumes that the gemfile and `version.rb` are in the same directory (same structure as e.g. for `thwait`).
**Please do not yet merge**, but update first to the latest core repository version of fileutils; this will probably cause a merge conflict and again break what I fixed in r64911; I will then fix the commit as necessary and repush the branch.
@hsbt

Use FileUtils::VERSION in gemspec

---

lib/fileutils.rb

* lib/fileutils.rb: [DOC] restore documentation for FileUtils module
which became undocumented with r63430.

Merge r64911: restore documentation for FileUtils

---

fileutils.gemspec

This PR is pretty much the same as https://github.com/ruby/logger/pull/7. There are some files like `.travis.yml` which do not need to be included in gem releases.

Remove development files in gem releases

---

lib/fileutils.rb

I think there is a good opportunity to improve the documentation of FileUtils, and i wanted to start with something simple.
This PR does a couple of things:
* Provide an example of the method in it's simplest possible form.
* Replace jargon with more more descriptive terms for better understanding for new developers
* General wording improvements
Thanks!

improve the documentation of FileUtils.cd

---

lib/fileutils.rb

`Dir.children` is only available on versions of MRI >= 2.5. This is breaking CI and preventing new PRs from being merged. This was caused by https://github.com/ruby/fileutils/commit/d8c665c564e5d4e54da1c92788613f524aad0de2
This PR fixes the issue by checking if the method exists, otherwise, use the previous way of getting filenames.

fix breaking specs in CI due to undefined method in ruby MRI < 2.5

---

lib/fileutils.rb

This helps `bundler` by not activating the `etc` gem automatically when it's vendored version of `fileutils` is required. That would allow `bundler` users to activate any version of the `etc` gem they want.

Lazily require `etc`

---

lib/fileutils.rb

This avoids searching the LOAD_PATH and it also helps `bundler` when vendoring this gem because it won't need to do any [modifications to the way it's required](https://github.com/bundler/bundler/blob/dd8e145596da7a9c93f11f42ce9196f591a3a6c8/lib/bundler/vendor/fileutils/lib/fileutils.rb#L9).

Require version file relatively

---

lib/fileutils.rb

This PR updates `FileUtils` docs. Initially, I just started to fix wrong example of usage of [cp_r](https://ruby-doc.org/stdlib-2.6.1/libdoc/fileutils/rdoc/FileUtils.html#method-c-cp_r), which started with:
```ruby
FileUtils.rm_r site_ruby + '/mylib', :force # doesn't work, should be force: true
```
...but then I reviewed the whole module docs and did the following changes:
* updated all code examples to use keyword args instead of hashrocket syntax;
* hidden some of internal constants and modules;
* made "See also" links linkable (see, for example, [rm_rf](https://ruby-doc.org/stdlib-2.6.1/libdoc/fileutils/rdoc/FileUtils.html#method-c-rm_rf) -- it says "Read the documentation of rm_r first.", but `rm_r` isn't linked, because in docs source it should be `documentation of rm_r` or …

Update the documentation content and formatting

---

lib/fileutils.rb
test/fileutils/test_fileutils.rb

Previously, this was broken.  Trying to copy a FIFO would raise a
NoMethodError if File.mkfifo was defined.  Trying to copy a UNIX
socket would raise a RuntimeError as File.mknod is not something
Ruby defines.
Handle the FIFO issue using File.mkfifo instead of mkfifo.
Handle the UNIX Socket issue by creating a unix socket.
Continue to not support character or block devices, raising a
RuntimeError for both.
Add tests for FIFO, UNIX Socket, and character/block devices.
Fixes Ruby Bug 10104.

Make copy methods handle FIFOs and UNIX sockets

---

lib/fileutils.rb
test/fileutils/test_fileutils.rb

If FileUtils is included into another object, and verbose mode is
used, a FrozenError is currently raised unless the object has the
@fileutils_output and @fileutils_label instance variables.
This fixes things so that it does not attempt to set the instance
variables, but it still uses them if they are present.

Do not break in verbose mode if using FileUtils with a frozen object

---

lib/fileutils.rb
test/fileutils/test_fileutils.rb

Fix cp_r with symlink root on Windows
Previously this would copy the symlink root as a symlink instead
of creating a new root directory.  This modifies the source
to expand it using File.realpath before starting the copy.
Fix test_cp_r_dev on Windows or other systems without
character/block device in /dev
Fixes Ruby Bug 12123

Fix a Couple Windows Issues

---

lib/fileutils.rb

Bump required_ruby_version so older ruby versions that may
depend on taint setting will not be affected.

Remove use of taint, to avoid deprecation warnings in Ruby 2.7

---

fileutils.gemspec
lib/fileutils.rb
lib/fileutils/version.rb

Loading separate version.rb unnecessary increases every start-up time.  In the other hand, the gemspec file is parsed only when building the gem file.

Remove version.rb

---

lib/fileutils.rb
test/fileutils/test_fileutils.rb

`FileUtils#install` methed raises an unexpected `TypeError`, when called with `mode:` option which has `"X"`.
```
$ ruby -rfileutils -e 'FileUtils.install("tmp/a", "tmp/b", mode: "o+X")'
/opt/local/lib/ruby/2.7.0/fileutils.rb:942:in `directory?': no implicit conversion of File::Stat into String (TypeError)
from /opt/local/lib/ruby/2.7.0/fileutils.rb:942:in `block (3 levels) in symbolic_modes_to_i'
from /opt/local/lib/ruby/2.7.0/fileutils.rb:933:in `each_char'
from /opt/local/lib/ruby/2.7.0/fileutils.rb:933:in `each'
from /opt/local/lib/ruby/2.7.0/fileutils.rb:933:in `inject'
from /opt/local/lib/ruby/2.7.0/fileutils.rb:933:in `block (2 levels) in symbolic_modes_to_i'
from /opt/local/lib/ruby/2.7.0/fileutils.rb:931:in `each'
from /opt/local/lib/ruby/2.7.0/fileutils.rb:931:in `each_slice' …
```

Fix `#install` with "X" mode option

---

test/lib/core_assertions.rb

These two commits should get CI green.
Fixes #44.

Fix Ruby 2.4 test run

---

lib/fileutils.rb
test/fileutils/test_fileutils.rb

Verbose output is not error output, and should be sent to
stdout and not stderr.
Fixes Ruby bug 4436

Make verbose output go to stdout instead of stderr

---

lib/fileutils.rb
test/fileutils/test_fileutils.rb

`FileUtils#install` methed raises an unexpected `TypeError`, when
called with `mode:` option which has `"X"`.
```
$ ruby -rfileutils -e 'FileUtils.install("tmp/a", "tmp/b", mode: "o+X")'
/opt/local/lib/ruby/2.7.0/fileutils.rb:942:in `directory?': no implicit conversion of File::Stat into String (TypeError)
from /opt/local/lib/ruby/2.7.0/fileutils.rb:942:in `block (3 levels) in symbolic_modes_to_i'
from /opt/local/lib/ruby/2.7.0/fileutils.rb:933:in `each_char'
from /opt/local/lib/ruby/2.7.0/fileutils.rb:933:in `each'
from /opt/local/lib/ruby/2.7.0/fileutils.rb:933:in `inject'
from /opt/local/lib/ruby/2.7.0/fileutils.rb:933:in `block (2 levels) in symbolic_modes_to_i'
from /opt/local/lib/ruby/2.7.0/fileutils.rb:931:in `each'
from /opt/local/lib/ruby/2.7.0/fileutils.rb:931:in `each_slice' …
```

Fix #install with "X" mode option

---

lib/fileutils.rb

By calling the instruction to `list.map` within `list.each` itself.

Reduce iteration through list for `:mkdir_p`

---

lib/fileutils.rb

Previously, if creating the directory directly didn't work
and the directory didn't exist, mkdir_p would create all
directories from the root.  This modifies the approach to
check whether the directory exists when walking up the
directory tree from the argument, and once you have found an
intermediate directory that exists, you only need to create
directories under it.
This approach has a couple advantages:
1) It performs better when most directories in path already exist,
and that will be true for most usage of mkdir_p, as mkdir_p is
usually called with paths where the first few directories exist
and only the last directory or last few directories do not.
2) It works in file-system access limited environments such as
when unveil(2) is used on OpenBSD.  In these environments, if …

Make mkdir_p only attempt to create necessary directories

---

lib/fileutils.rb

Treats:
- ::pwd
- ::cd
- ::uptodate?
- ::mkdir

Enhanced RDoc for FileUtils

---

lib/fileutils.rb

[DOC] Enhanced RDoc for FileUtils

---

lib/fileutils.rb

This PR experiments with using ```tree``` to display directory structure (both src and dest).  If we decide to keep this, we'll need to add a note about tree in the intro.

[DOC] Enhanced RDoc for copy_entry

---

lib/fileutils.rb

Treats:
- ::copy_entry
- ::copy_file
- ::copy_stream
- ::mv

[DOC] Enhanced RDoc

---

lib/fileutils.rb

Adds a note about file tree examples.

[DOC] Beautify file trees

---

lib/fileutils.rb

There are nearly 30 methods that take path arguments (String, File, Dir, or Pathname).  Previously we had Pathname examples for only three of those.  I think we should have Pathname examples either for all of them or for none of them.  Thoughts?

[DOC] Clarify path arguments

---

lib/fileutils.rb

I have not provided an example for cp_r with multiple dirpaths in +src+ b/c it would be huge.  Should I add one?
If +src+ is an array of paths and +dest+ is a directory,
recursively copies from each path in +src+ to +dest+;
the paths in +src+ may point to files and/or directories.

[DOC] More on cp_r

---

lib/fileutils.rb

Small tweaks:
- Adds return values.
- Adds aliases.

[DOC] Small tweaks

---

lib/fileutils.rb

Next PR will have "What's Here" section.  Any thoughts about the ordering of the sections?

[DOC] Revisions for module-level doc

---

lib/fileutils.rb

These are just for the deleters (more to come).  There are so many of these, closely related, that it may make sense to link to the Deleting section in What's Here.

Adding 'Related'

---

lib/fileutils.rb

Change two references to C methods `chown` and `chmod` to refer instead to Ruby methods `File#chown` and `File#chmod` (which are those actually called).

[DOC] Correct method references for secure removal

---

lib/fileutils.rb

Uses tree in examples for FileUtils.cp_lr.
Retains `File.exist?` only when the result will be `true`; otherwise changes to `File.file?` or `File.directory?`, which is more precise.

[DOC] Changes to examples

---

lib/fileutils.rb
test/fileutils/test_fileutils.rb

FileUtils.rm_rf should ignore only Errno::ENOENT, not StandardError

---

lib/fileutils.rb
test/fileutils/test_fileutils.rb

This reverts commit fa65d676ece93a1380b9e6564efa4b4566c7a44b.
This caused some incompatibility problems in real-world cases.
* https://bugs.ruby-lang.org/issues/18784#change-98927
* https://bugs.ruby-lang.org/issues/18784#change-98967

Revert "FileUtils.rm* methods swallows only Errno::ENOENT when force is true"

---

lib/fileutils.rb
test/fileutils/test_fileutils.rb

[Feature #18925] Add `ln_sr` method and `relative:` option to `ln_s`

---

lib/fileutils.rb
test/fileutils/test_fileutils.rb

In this case, an ArgumentError is now raised rather than ignoring the option, just as GNU coreutils' `ln` would error on the command line.
Fixes #128 as well.

Fix `ln_sf` with multiple sources and `target_directory: false`

---

lib/fileutils.rb

Several optional positional arguments were incorrectly denoted as keyword arguments so correct them.

[DOC] Fix optional argument descriptions

---

lib/fileutils.rb

If `noop`, return before checking the argument
